spring.application.name=migrations-liquibase

spring.datasource.url=jdbc:postgresql://localhost:5434/bookstore
spring.datasource.username=kainom
spring.datasource.password=luadourada123


spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27016/bookstore

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.liquibase.enabled=true

spring.jpa.defer-datasource-initialization=false 
